### ISSUE TITLE
could you share me the pre-trained model

### ISSUE THREAD

**Issue by kingrain213** [mahmoudmohsen213/airs#1]

**Comment by kingrain213** [comment]
1）could you tell me the  format of test.csv、 train.csv、valid.csv？so I make the csv file and train a new model;
2)could you share me your pre-trained model?when I run  "python classify.py 10228690_15.jpg tt.jpg"   It failed with "Couldn't find trained model at model."

**Comment by mahmoudmohsen213** [comment]
### The csv files follow a very simple format:
- each record (line) is a single feature vector with its ground truth outcome.
- each feature vector consists of the RGB values of pixels contained in a 5x5 window (three numbers for each pixel), and a binary value representing the class of the central pixel of that window.

Accordingly, each line in the csv files should consist of (3x5x5) + 1 numbers as follows:
```
r1, g1, b1, r2, g2, b2, r3, g3, b3, . . . . . , r25, g25, b25, y
```
Where r13, g13, b13, are the RGB values of the central pixel, and y is the class of the central pixel.
The pixels in the window are ordered in the feature vector in row-major order.

### Could you share me your pre-trained model:
It can be managed, if you have enough cloud storage where I can share it with you, because the trained model as saved by tensorflow is 846 MB, also it will take ages to upload :smile:

### When I run "python classify.py 10228690_15.jpg tt.jpg" It failed with "Couldn't find trained model at model.":
The message you are seeing is not printed in classify.py, so most probably it's printed by tensorflow itself. This happens because classify.py tries to use the classifier after loading it.

classify.py will tell tensorflow to look for a trained model in a directory with the name 'model' in the same current working directory of the script being executed. If you are using the same versions of the libraries, and the files in 'model' directory is in the same format as saved by tensorflow, this porblem should not happen.

The files in the model directory as saved by tensorflow should look like this:
```
model
  |-eval
  |  |-events.out.tfevents.1496920307.PC_NAME
  |
  |-checkpoint
  |-events.out.tfevents.1496913315
  |-graph.pbtxt
  |-model.ckpt-1001.data-00000-of-00001
  |-model.ckpt-1001.index
  |-model.ckpt-1001.meta
  |-model.ckpt-2001.data-00000-of-00001
  |-model.ckpt-2001.index
  |-model.ckpt-2001.meta
```

Please be careful with which tensorflow version you are using, because I think it's still under development, with lots of rapid changes.

Sorry for my late reply :smile:

**Comment by skeeph** [comment]
@mahmoudmohsen213 could you to download pretrained model to Dropbox, for example?

**Comment by mahmoudmohsen213** [comment]
@skeeph @kingrain213 here you go https://www.dropbox.com/s/qiot4657pa4a7rb/airs-model.zip?dl=0
