### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by haoyongdong** [mahmoudmohsen213/airs#4]
I run convertFeatureFiles.py according to your method but the data is not written to the csv file
![{K03@L@SVA2W{NEQ`(0OKYF](https://user-images.githubusercontent.com/57824480/77165971-55a72700-6aee-11ea-8f3f-38fbf2d9138b.png)

**Comment by haoyongdong** [comment]
Stop here, no data is written to csv
![8N{`IVIBGQJ`T}RIE~27VA0](https://user-images.githubusercontent.com/57824480/77169980-5a230e00-6af5-11ea-992f-2005117ab7ee.png)

**Comment by mahmoudmohsen213** [comment]
If you take a look at any real aerial images data set, you will notice that the number of non-road pixels is greater than the number of road pixels by an overwhelming difference.

So, to prevent over fitting, I wrote the code to take only 2 non-road pixels for each 1 road pixel, so that the feature vector of the output csv files will always have a ratio of `non-road:road` = `2:1`.

To do this, for each 1 road pixel feature vector written to the csv file [here](https://github.com/mahmoudmohsen213/airs/blob/master/convertToFeatureFiles.py#L159), 2 non-road pixel feature vectors are consumed from the `outputImageNonRoadPixelsArr` by the `for` loop that starts [here](https://github.com/mahmoudmohsen213/airs/blob/master/convertToFeatureFiles.py#L161), and you will notice that it computes the indices of the non-road pixels that should be consumed using an equation.

To prevent an out-of-bound access by this equation, the index of the current road pixel must be less than half the number of non-road pixels, specifically, this condition must hold:
```py
((m*2) + 1) < len(outputImageNonRoadPixelsArr)
```

Here is what you need to do:
1. Check if [this loop](https://github.com/mahmoudmohsen213/airs/blob/master/convertToFeatureFiles.py#L137) executes at least one iteration.
2. If no, then your input images don't have enough non-road pixels to meet my ratio condition, so you either modify the code to ignore this ratio, or change the input images.
3. If yes, then I guess there is a problem with writing to the file and breaking the loop, buffering problem maybe?! But this didn't happen with me so I'll be a bit surprised.

> Please note that the code determines if a pixel is a road pixel or not using the output image binary mask, so you may also need to check on that.

**Comment by haoyongdong** [comment]
I just used your input sample image, but still there is no way to write to the file

**Comment by mahmoudmohsen213** [comment]
Did you do the debugging steps I mentioned earlier? You need to check if the loop executes at least one iteration. And if it doesn't, check on the size of the non-road pixels array, if it is empty, then there must be something wrong with the input.

**Comment by mahmoudmohsen213** [comment]
Btw, It is not recommended to run the code with the sample images included, I included them only to demonstrate the directory and file naming structure, try using the original data set images.
